"""Medical report generation service.

Generates a professional, Markdown medical report for a prediction **only**
through the :class:`AIProvider` abstraction — no vendor SDK is imported here, so
switching ``LLM_PROVIDER`` in the environment changes the model with zero code
change. The clinical ``risk_level`` is derived deterministically from the
prediction (never trusted to the LLM); the LLM writes only the narrative
(see ``docs/09_AI_Architecture.md``).
"""

from __future__ import annotations

from app.core.config import Settings
from app.core.logging import get_logger
from app.domain.entities.prediction import Prediction
from app.domain.entities.report import Report
from app.domain.ports.llm_provider import AIProvider
from app.domain.value_objects.risk_level import RiskLevel

logger = get_logger(__name__)

_HIGH_CONFIDENCE = 0.85
_DISCLAIMER = (
    "This report is generated by an AI decision-support system and is not a "
    "medical diagnosis. It must be reviewed and confirmed by a licensed clinician."
)

_SYSTEM_PROMPT = (
    "You are a radiology assistant producing a structured, professional medical "
    "report for a chest X-ray pneumonia screening model. Write in clear clinical "
    "Markdown with these sections: Summary, Findings, Possible Condition, Medical "
    "Explanation, Recommendations, Risk Level, Disclaimer. Be factual and cautious; "
    "never state a definitive diagnosis. Always include the disclaimer verbatim."
)


def derive_risk_level(prediction: Prediction) -> RiskLevel:
    """Derive the clinical risk band deterministically from a prediction."""
    if prediction.ood_flag:
        return RiskLevel.MODERATE
    if prediction.predicted_class.upper() == "PNEUMONIA":
        return RiskLevel.HIGH if prediction.confidence >= _HIGH_CONFIDENCE else RiskLevel.MODERATE
    return RiskLevel.LOW


class ReportService:
    """Builds medical reports via the LLM provider abstraction."""

    def __init__(self, llm_provider: AIProvider, settings: Settings) -> None:
        self._llm = llm_provider
        self._settings = settings

    def _build_prompt(self, prediction: Prediction, risk_level: RiskLevel) -> str:
        """Assemble the provider-agnostic report prompt (Builder pattern)."""
        probabilities = ", ".join(
            f"{label}: {value:.1%}" for label, value in prediction.probabilities.items()
        )
        ood_note = (
            "The input was flagged as possibly out-of-distribution (it may not be a "
            "standard chest X-ray); interpret results with extra caution.\n"
            if prediction.ood_flag
            else ""
        )
        return (
            f"Model architecture: {prediction.model_arch} ({prediction.model_version}).\n"
            f"Predicted class: {prediction.predicted_class}.\n"
            f"Confidence: {prediction.confidence:.1%}.\n"
            f"Class probabilities: {probabilities}.\n"
            f"Derived risk level: {risk_level.value}.\n"
            f"{ood_note}"
            f"Write the structured medical report now. End with this disclaimer "
            f"verbatim: \"{_DISCLAIMER}\""
        )

    async def generate(self, prediction: Prediction) -> Report:
        """Generate and return a :class:`Report` for ``prediction``.

        The report is not persisted here; the caller owns persistence.
        """
        risk_level = derive_risk_level(prediction)
        prompt = self._build_prompt(prediction, risk_level)
        content = await self._llm.generate(prompt, system=_SYSTEM_PROMPT, temperature=0.2)
        logger.info(
            "report.generated",
            prediction_id=prediction.id,
            provider=self._llm.name,
            risk_level=risk_level.value,
        )
        return Report(
            prediction_id=prediction.id or "",
            user_id=prediction.user_id,
            llm_provider=self._llm.name,
            llm_model=self._settings.llm_model,
            content_markdown=content,
            risk_level=risk_level,
            sections={
                "predicted_class": prediction.predicted_class,
                "confidence": f"{prediction.confidence:.4f}",
                "disclaimer": _DISCLAIMER,
            },
        )
