"""Training artifact generation: curves, confusion matrix, metrics JSON, summary."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np


def _use_headless_matplotlib() -> Any:
    """Import matplotlib with a non-interactive backend."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    return plt


def save_curves(history: list[dict[str, float]], out_dir: Path) -> tuple[Path, Path]:
    """Save loss and accuracy curves; return the two image paths."""
    plt = _use_headless_matplotlib()
    epochs = [row["epoch"] for row in history]

    loss_path = out_dir / "loss_curve.png"
    plt.figure(figsize=(6, 4))
    plt.plot(epochs, [r["train_loss"] for r in history], label="train")
    plt.plot(epochs, [r["val_loss"] for r in history], label="val")
    plt.xlabel("epoch")
    plt.ylabel("loss")
    plt.title("Training / validation loss")
    plt.legend()
    plt.tight_layout()
    plt.savefig(loss_path, dpi=120)
    plt.close()

    acc_path = out_dir / "accuracy_curve.png"
    plt.figure(figsize=(6, 4))
    plt.plot(epochs, [r["train_acc"] for r in history], label="train")
    plt.plot(epochs, [r["val_acc"] for r in history], label="val")
    plt.xlabel("epoch")
    plt.ylabel("accuracy")
    plt.title("Training / validation accuracy")
    plt.legend()
    plt.tight_layout()
    plt.savefig(acc_path, dpi=120)
    plt.close()
    return loss_path, acc_path


def save_confusion_matrix(
    matrix: list[list[int]], class_names: list[str], out_dir: Path
) -> Path:
    """Render the confusion matrix as an annotated image."""
    plt = _use_headless_matplotlib()
    data = np.array(matrix)
    path = out_dir / "confusion_matrix.png"
    fig, ax = plt.subplots(figsize=(4.5, 4))
    ax.imshow(data, cmap="Blues")
    ax.set_xticks(range(len(class_names)), labels=class_names)
    ax.set_yticks(range(len(class_names)), labels=class_names)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    ax.set_title("Confusion matrix")
    for i in range(len(class_names)):
        for j in range(len(class_names)):
            ax.text(j, i, str(data[i, j]), ha="center", va="center",
                    color="white" if data[i, j] > data.max() / 2 else "black")
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)
    return path


def save_metrics_json(metrics: dict[str, Any], out_dir: Path) -> Path:
    """Write the metrics report as JSON."""
    path = out_dir / "metrics.json"
    path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    return path


def save_summary_markdown(
    *,
    config: dict[str, Any],
    stats: dict[str, Any],
    metrics: dict[str, Any],
    best_epoch: int,
    version: int,
    out_dir: Path,
) -> Path:
    """Write a human-readable training summary in Markdown."""
    path = out_dir / "training_summary.md"
    per_class = "\n".join(
        f"| {name} | {m['precision']} | {m['recall']} | {m['f1']} | {m['support']} |"
        for name, m in metrics["per_class"].items()
    )
    content = f"""# Training Summary — {config['arch']} v{version}

**Dataset:** {config['dataset_name']}  ·  **Best epoch:** {best_epoch}

## Dataset statistics
- Total images: {stats['total']}
- Splits: {stats['per_split']}
- Classes: {stats['per_class']}

## Test metrics
| Metric | Value |
|--------|-------|
| Accuracy | {metrics['accuracy']} |
| Precision (PNEUMONIA) | {metrics['precision']} |
| Recall (PNEUMONIA) | {metrics['recall']} |
| F1 (PNEUMONIA) | {metrics['f1']} |
| F1 (macro) | {metrics['f1_macro']} |
| ROC-AUC | {metrics['roc_auc']} |

### Per-class
| Class | Precision | Recall | F1 | Support |
|-------|-----------|--------|----|---------|
{per_class}

## Key hyperparameters
- Architecture: {config['arch']} (pretrained={config['pretrained']})
- Epochs: {config['epochs']}, batch size: {config['batch_size']}
- Learning rate: {config['learning_rate']}, weight decay: {config['weight_decay']}
- Scheduler: {config['scheduler']}, early-stopping patience: {config['early_stopping_patience']}
- Image size: {config['image_size']}, seed: {config['seed']}

_Generated by the AIMIP training pipeline. Decision-support only; not a medical device._
"""
    path.write_text(content, encoding="utf-8")
    return path
